server:
  port: 9000

spring:
  rabbitmq:
    # 主机地址
    host: 101.35.155.147
    # 虚拟主机
    virtual-host: test_host
    # 端口号默认是5672，可以不写
    port: 5672
    # 用户名
    username: test
    # 密码
    password: 123456
    # 开启发送端确认机制
    publisher-confirm-type: correlated
    # 开启发送端消息抵达队列的确认
    publisher-returns: true
    # 只要消息抵达队列，就以异步方式优先回调returnConfirm
    template:
      mandatory: true